apiVersion: v1
kind: Service
metadata:
  name: football-match-scores-service
  labels:
    app: football-match-scores
spec:
  type: NodePort
  selector:
    app: football-match-scores
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080